function [T, M, boil_time] = solar_cooker_sim(cooker_radius)
    pot_radius = 8/100; % m
    pot_height = 8/100; % m
    pot_thickness = 0.05/100; % m
    h_water = 250; % J/(kg*K)
    h_air = 25; % J/(kg*K)
    air_temp = 270; % K
    A_top_pot = (pot_radius)^2 * pi; % m^2
    A_inner_pot = (pot_radius)*2*pi*pot_height + A_top_pot; % m^2
    A_outer_pot = (pot_radius+pot_thickness)*2*pi*pot_height + (pot_radius+pot_thickness)^2*pi; % m^2
    A_proj_cooker = cooker_radius^2 * pi; % m^2
    V_water = A_top_pot*(pot_height); % m^3
    V_pot = (pot_radius+pot_thickness)^2*pi*(pot_height+pot_thickness) - V_water; % m^3
    rho_pot = 8050; % kg/m^3
    rho_water = 1000; % kg/m^3
    e_pot = 0.5;
    e_water = 0.5;
    I = 2000; % W/m^2 TODO adjust
    m_pot = rho_pot*V_pot; % kg
    c_pot = 490; % J/(K*kg)
    m_water = rho_water*V_water; % kg
    c_water = 4186; % J/(K*kg)
    function res = rate_func(~, X)
        res = zeros(2, 1);
        pot_temp = energyToTemperature(X(1), m_pot, c_pot);
        water_temp = energyToTemperature(X(2), m_water, c_water);
        diff_temp_pot_air = air_temp - pot_temp;
        U_conv_water = (h_water*A_inner_pot) * (pot_temp - water_temp);
        res(1) = e_pot*I*A_proj_cooker - U_conv_water;
        res(2) = U_conv_water + e_water*I*A_top_pot;
    end
    U_pot_0 = temperatureToEnergy(air_temp, m_pot, c_pot);
    U_water_0 = temperatureToEnergy(air_temp, m_water, c_water);
    t_0 = 0;
    t_end = 15*60;
    [T, M] = ode45(@rate_func, [t_0, t_end], [U_pot_0; U_water_0]);
    M(:, 1) =  energyToTemperature(M(:, 1), m_pot, c_pot);
    M(:, 2) =  energyToTemperature(M(:, 2), m_water, c_water);
    T = T/60;
    boil_temp = 373; % K
    [~, boil_ind] = max(M(1:find(M(:,2) > boil_temp, 1),2));
    boil_time = T(boil_ind);
end